export const data = [
  {
    ID: 1,
    HeadID: -1,
    Entity: 'Gronw Kapila',
    RequestDate: '2022-06-01',
    RequestStatus: 'Open',
    ResponseDate: null,
    ResponseStatus: 'New',
  },
  {
    ID: 2,
    HeadID: 1,
    Entity: 'Sigurd Gwalchmei',
    RequestDate: '2022-06-02',
    RequestStatus: 'Open',
    ResponseDate: null,
    ResponseStatus: 'New',
  },
  {
    ID: 3,
    HeadID: 1,
    Entity: 'Frigg Camilla',
    RequestDate: '2022-06-02',
    RequestStatus: 'Open',
    ResponseDate: null,
    ResponseStatus: 'New',
  },
  {
    ID: 4,
    HeadID: 1,
    Entity: 'Gwawl Nisus',
    RequestDate: '2022-06-02',
    RequestStatus: 'Open',
    ResponseDate: null,
    ResponseStatus: 'New',
  },
  {
    ID: 5,
    HeadID: 2,
    Entity: 'Yemanjá Amor',
    RequestDate: '2022-06-05',
    RequestStatus: 'Open',
    ResponseDate: null,
    ResponseStatus: 'New',
  },
  {
    ID: 6,
    HeadID: 2,
    Entity: 'Cardea Quirinus',
    RequestDate: '2022-06-05',
    RequestStatus: 'Open',
    ResponseDate: null,
    ResponseStatus: 'New',
  },
  {
    ID: 7,
    HeadID: 3,
    Entity: 'Heber Ianthe',
    RequestDate: '2022-06-04',
    RequestStatus: 'Open',
    ResponseDate: null,
    ResponseStatus: 'New',
  },
  {
    ID: 8,
    HeadID: 4,
    Entity: 'Caishen Urania',
    RequestDate: '2022-06-08',
    RequestStatus: 'Closed',
    ResponseDate: '2022-06-22',
    ResponseStatus: 'Submitted',
  },
  {
    ID: 9,
    HeadID: 8,
    Entity: 'Lamia Bahram',
    RequestDate: '2022-06-10',
    RequestStatus: 'Closed',
    ResponseDate: '2022-06-20',
    ResponseStatus: 'Submitted',
  },
];
